# Generated by Django 6.0.3 on 2026-03-25 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="featurerequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="featurerequest",
            name="vote_count",
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feature_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="core.featurerequest",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["session_key"], name="core_vote_session_4eca52_idx"
                    )
                ],
                "unique_together": {("feature_request", "session_key")},
            },
        ),
    ]
